---
level: easy
tags: []
description: |
  I like big stacks and I cannot lie
  All you other developers can't deny
  That linked lists have too much hype
  And you'd rather use a last-in-first-out datatype

multicode_checks:
  langs: [ruby, javascript, coffeescript, php, python]
